# Change these first
owner: TecnicaMilar # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Pagina Web
    url: https://milar.farm
    __dangerous__insecure: true
  - name: Sniper
    url: https://sniper.milar.farm/login
 

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.milar.farm
  # baseUrl: /your-repo-name
  logoUrl: https://milar.farm/wp-content/uploads/2021/06/Logo-Milar.png
  name: 
  theme: dark
  introTitle: "**Status** Monitoreo de nuestras soluciones."
  introMessage: Pagina de monitoreo **real-time** del estado de nuestros servicios
  navbar:
    - title: Status
      href: /
    - title: Pagina Web
      href: https://milar.farm

i18n:
    activeIncidents: Incidente Activo
    allSystemsOperational: Todos los sistemas se encuentan operativos
    incidentReport: "Incidente #$NUMBER reportado →"
    activeIncidentSummary: Abierto el $DATE con $POSTS publicaciones
    incidentTitle: Incidente $NUMBER Detalle
    incidentDetails: Detalle de Incidente
    incidentFixed: Arreglado
    incidentOngoing: Saliente
    incidentOpenedAt: Abierto el
    incidentClosedAt: Cerrado el
    incidentSubscribe: Subscribete para Actualizaciones
    incidentViewOnGitHub: Ver en GitHub
    incidentCommentSummary: Publicado el $DATE por $AUTHOR
    incidentBack: ← Volver a todos los incidentes
    pastIncidents: Incidentes Pasados
    pastIncidentsResolved: Resuelto en $MINUTES minutos con $POSTS publicaciones
    liveStatus: Estado Actual
    overallUptime: "Porcentaje de Actividad: $UPTIME"
    overallUptimeTitle: Porcentaje de Actividad
    averageResponseTime: "Tiempo de respuesta: $TIMEms"
    averageResponseTimeTitle: Tiempo de respuesta
    sevelDayResponseTime: Tiempo de respuesta de los últimos 7 dias
    responseTimeMs: Tiempo de respuesta (ms)
    up: Activo
    down: Inactivo
    degraded: Degradado
    ms: ms
    loading: Cargando
    errorTitle: Ocurrio un error
    errorIntro: Ocurrio un error intentando obtener el detalle del ultimo estado.
    errorText: Puede intentarlo nuevamente en unos minutos.
    errorHome: Ir a la pagina principal
    pastScheduledMaintenance: Fin del Mantenimiento Programado
    scheduledMaintenance: Mantenimiento Programado
    scheduledMaintenanceSummaryStarted: Comenzo el $DATE por $DURATION minutos
    scheduledMaintenanceSummaryStarts: Comienza el $DATE for $DURATION minutes
    startedAt: Comenzo a
    startsAt: Comienza a
    duration: Duracion
    durationMin: $DURATION minutos
    incidentCompleted: Completada
    incidentScheduled: Programada

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
